<?php echo $this->doctype('XHTML1_STRICT');?>
<html>
    <head>
        <?php echo $this->headTitle('LoudBite.com - Remove Artist');?>
    </head>
</html>
<body>
    <?php echo $this->render('includes/header.phtml'); ?>
    <h3>Remove Artist</h3>
    <table>
        <tr>
            <td>Artists - <i> Total Artist(<?php echo $this->totalArtist;?>)</i></td>
        </tr>
        <?php foreach($this->artists as $artist) { ?>
        <tr>
            <td>
                <input type="checkbox" value="<?php echo $this->escape($artist["name"]) ?>" name="remove[]" />
                <?php echo $this->escape($artist["name"])?>
                <?php if($artist["rating"]==5){ ?>*<?php } ?>
            </td>
        </tr>
        <?php }?>
        <tr>
            <td><input type="submit" value="Remove" /></td>
        </tr>
    </table>
</body>