<?php echo $this->doctype('XHTML1_STRICT');?>
<html xmlns="http://www.w3.org/" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headTitle('LoudBite.com - Add Artist'); ?>
    </head>
    <body>
        <?php $this->render('includes/header.phtml') ?>
        <h3>Add Artist</h3>
        <p>
            Thank you. The artist has successfully save. <br />
            <a href="new">Add another artist</a>
        </p>
    </body>
</html>